SELECT 
    a.*,
    c.num_matricula_registro_civil,
    c.num_termo,
    c.livro,
    c.folha,
    c.data_expedicao_certidao,
    s.autismo,
    s.rett,
    s.asperger,
    s.transtorno_desintegrativo,
    s.baixa_visao,
    s.cegueira,
    s.auditiva,
    s.intelectual,
    s.fisica,
    s.multipla,
    s.sindrome_down,
    s.surdez,
    s.surdocegueira,
    s.altas_habilidades,
    e.endereco,
    e.complemento,
    e.numero_endereco,
    e.municipio,
    e.bairro,
    e.cep,
    e.zona,
    e.telefone,
    e.email,
	e.uf as endereco_uf,
    p.nome_mae,
    p.nome_pai,
    m.nome_escola,
    m.cod_censo_inep,
    m.data_ingresso_escola,
    m.matricula,
    m.data_matricula,
    m.codigo_turma,
    m.turno,
    m.codigo_serie,
    m.codigo_procedencia,
    m.participa_programa,
    m.transporte_escolar,
    m.ano_letivo
FROM identificacao_aluno a
LEFT JOIN certidao c ON a.id_aluno = c.id_aluno
LEFT JOIN saude s ON a.id_aluno = s.id_aluno
LEFT JOIN endereco e ON a.id_aluno = e.id_aluno
LEFT JOIN dados_pais_responsavel p ON a.id_aluno = p.id_aluno
LEFT JOIN informacoes_matricula m ON a.id_aluno = m.id_aluno;
